const g_data = {

    contacts: [
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-1', tel: 'XXX-NNN-YYY', city: 'city-1', info: 'text-1' },
        { name: 'guest-N', tel: 'OOO-QQQ-DDD', city: 'city-N', info: 'text-N' }
    ]
}